version: '3.8'
services: 
  socialnetwork:
    container_name: socialnetwork-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: alex
      MYSQL_DATABASE: serverdb
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-db.d/0_init.sql
      - $HOME/socialnetwork_database:/var/lib/mysql
    networks:
      - socialnet

networks:
  socialnet:
    driver: bridge