version: '3.8'
services: 
  socialnetwork:
    container_name: socialnetwork-app
    build: ./
    image: socialnetwork-app-image
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data:/var/lib/mysql
    networks:
      - socialnet

volumes:
  data:

networks:
  socialnet:
    driver: bridge